### Task 생성 API (POST)
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "projectId": 1,
  "title": "플로빗 첫 작업",
  "description": "Task 생성 테스트",
  "assigneeId": 1,
  "priority": 1
}

### [READ] Task 전체 조회
GET http://localhost:8080/tasks

### [READ] Task 단건 조회
GET http://localhost:8080/tasks/1